name: Build Ghostscript for OpenHarmony

on:
  workflow_dispatch:
  push:
    paths:
      - 'native/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: silkeh/clang:15  # 预装完整 LLVM 工具链

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ========== 安装基础构建工具 ==========
    - name: Install essential tools
      run: |
        apt-get update
        apt-get install -y git cmake ninja-build build-essential autoconf automake libtool pkg-config
        echo "工具安装完成: $(git --version), $(cmake --version | head -1)"

    # ========== 从源码构建鸿蒙系统组件 ==========
    - name: Build OpenHarmony sysroot
      run: |
        # 创建基础目录结构
        mkdir -p ohos-ndk/sysroot/{usr/include,usr/lib}
        OHOS_NDK=$PWD/ohos-ndk
        
        # 获取鸿蒙内核头文件 (使用 wget 代替 git)
        wget https://gitee.com/openharmony/kernel_liteos_a/repository/archive/master.tar.gz?format=tar.gz -O kernel.tar.gz
        tar -xzf kernel.tar.gz
        cp -r kernel_liteos_a/kernel/include/* $OHOS_NDK/sysroot/usr/include/
        
        # 下载 musl libc 源码
        wget https://gitee.com/openharmony/third_party_musl/repository/archive/master.tar.gz?format=tar.gz -O musl.tar.gz
        tar -xzf musl.tar.gz
        cd third_party_musl
        
        # 构建 musl libc
        ./configure \
          --target=aarch64-linux-ohos \
          --prefix=$OHOS_NDK/sysroot/usr \
          --disable-shared \
          --enable-static
        make -j$(nproc) install
        cd ..
        
        # 构建基础库 (使用 wget 下载)
        build_lib() {
          wget $1/repository/archive/master.tar.gz?format=tar.gz -O lib.tar.gz
          tar -xzf lib.tar.gz
          cd $(ls -d */ | head -1)
          mkdir build && cd build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=$OHOS_NDK/sysroot/usr \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_SYSROOT=$OHOS_NDK/sysroot \
            -DCMAKE_C_FLAGS="--target=aarch64-linux-ohos" \
            -DCMAKE_CXX_FLAGS="--target=aarch64-linux-ohos"
          cmake --build . --target install
          cd ../..
        }
        
        build_lib https://gitee.com/openharmony/third_party_zlib
        build_lib https://gitee.com/openharmony/third_party_libpng
        build_lib https://gitee.com/openharmony/third_party_freetype

        echo "OHOS_NDK_HOME=$OHOS_NDK" >> $GITHUB_ENV
        echo "PATH=$PATH:$OHOS_NDK/llvm/bin" >> $GITHUB_ENV

    # ========== 构建鸿蒙专用 Clang 工具链 ==========
    - name: Build OpenHarmony toolchain
      run: |
        OHOS_NDK=$OHOS_NDK_HOME
        
        # 下载 LLVM 源码 (使用 wget)
        wget https://github.com/llvm/llvm-project/archive/refs/heads/main.tar.gz -O llvm.tar.gz
        tar -xzf llvm.tar.gz
        cd llvm-project-main
        
        # 编译 Clang
        mkdir build && cd build
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_TARGETS_TO_BUILD="AArch64" \
          -DLLVM_ENABLE_PROJECTS="clang;lld" \
          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
          -DLLVM_DEFAULT_TARGET_TRIPLE=aarch64-linux-ohos \
          -DCMAKE_INSTALL_PREFIX=$OHOS_NDK/llvm \
          -DLLVM_BUILD_RUNTIME=OFF \
          ../llvm
        ninja install
        cd ../..
        
        # 创建 wrapper 脚本
        cat > $OHOS_NDK/llvm/bin/aarch64-linux-ohos-clang <<'EOF'
        #!/bin/bash
        exec $PWD/ohos-ndk/llvm/bin/clang \
          --target=aarch64-linux-ohos \
          --sysroot=$PWD/ohos-ndk/sysroot \
          -fuse-ld=lld \
          "$@"
        EOF
        chmod +x $OHOS_NDK/llvm/bin/aarch64-linux-ohos-clang*
        ln -s aarch64-linux-ohos-clang $OHOS_NDK/llvm/bin/aarch64-linux-ohos-clang++

    # ========== Ghostscript 交叉编译 ==========
    - name: Build Ghostscript
      run: |
        # 下载 Ghostscript 源码 (使用 wget)
        wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs1003/ghostscript-10.03.0.tar.gz
        tar -xzf ghostscript-10.03.0.tar.gz
        cd ghostscript-10.03.0
        
        # 应用鸿蒙适配补丁
        cat > ohos.patch <<'EOPATCH'
        diff --git a/base/gp_getnv.c b/base/gp_getnv.c
        index 1234567..89abcde 100644
        --- a/base/gp_getnv.c
        +++ b/base/gp_getnv.c
        @@ -22,6 +22,9 @@
         const char *
         gp_getenv(const char *key)
         {
        +    /* OpenHarmony doesn't have environment variables */
        +    return NULL;
        +
         #ifdef __APPLE__
             /* On macOS, when running in a sandbox, the environment is sanitized. */
             if (strcmp(key, "HOME") == 0)
        diff --git a/base/gp_unix.c b/base/gp_unix.c
        index 7654321..fghijkl 100644
        --- a/base/gp_unix.c
        +++ b/base/gp_unix.c
        @@ -83,7 +83,7 @@
         FILE *
         gp_fopen(const char *fname, const char *mode)
         {
        -    return fopen(fname, mode);
        +    return ohos_fopen(fname, mode); // 使用自定义实现
         }
        EOPATCH
        
        git apply ohos.patch || patch -p1 < ohos.patch
        
        # 添加简化版鸿蒙文件IO实现
        cat > base/ohos_fileio.c <<'EOF'
        #include <stdio.h>
        
        FILE* ohos_fopen(const char* path, const char* mode) {
            // 实际项目中应替换为鸿蒙API
            return fopen(path, mode);
        }
        EOF
        
        ./autogen.sh
        ./configure \
          --host=aarch64-linux-ohos \
          --prefix=/gs-build \
          --enable-shared \
          --disable-cups \
          --with-drivers=PCLm \
          CC="$OHOS_NDK_HOME/llvm/bin/aarch64-linux-ohos-clang" \
          CXX="$OHOS_NDK_HOME/llvm/bin/aarch64-linux-ohos-clang++" \
          CFLAGS="-fPIC -O3 -I$OHOS_NDK_HOME/sysroot/usr/include -DOHOS_CUSTOM_IO" \
          LDFLAGS="-L$OHOS_NDK_HOME/sysroot/usr/lib -lz -lpng -lfreetype"
        
        make -j$(nproc)
        make install

    # ========== 产物打包 ==========
    - name: Package artifacts
      run: |
        mkdir -p artifacts/libs/arm64-v8a
        cp /gs-build/lib/libgs.so artifacts/libs/arm64-v8a/
        
        # 验证文件类型
        file artifacts/libs/arm64-v8a/libgs.so
        echo "构建时间: $(date)" > artifacts/build-info.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ohos-ghostscript
        path: artifacts
