# .github/workflows/build.yml
name: Build and Upload Artifacts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-libs:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: libs-so

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgs-dev ghostscript libnode-dev

      - name: Build native
        working-directory: native
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel

      - name: Collect SO files
        run: |
          mkdir -p so
          cp native/build/gs_napi.so so/
          cp /usr/lib/x86_64-linux-gnu/libgs.so so/

      - name: Upload SO artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build-libs.outputs.artifact_name }}
          path: so/
