name: Build HarmonyOS HAP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_harmony:
    runs-on: ubuntu-latest
    env:
      HAP_PROJECT_DIR: harmony-module   # adjust if your module folder name is different
      HAP_CPP_DIR: native/cpp           # set this to the real path under HAP_PROJECT_DIR
      HAP_OUTPUT: ${{ github.workspace }}/harmony-module/output

    steps:
      - uses: actions/checkout@v4

      - name: Debug workspace layout
        run: ls -R ${{ github.workspace }}

      - name: Build native C++ plugin
        run: |
          cd ${{ github.workspace }}/${{ env.HAP_PROJECT_DIR }}/${{ env.HAP_CPP_DIR }}
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DHOS_ARCH=arm64-v8a \
            -DGS_SHARED=ON \
            -DGS_LIB_PATH="${{ github.workspace }}/libgs.so"
          make -j$(nproc)
          mkdir -p ../libs/arm64-v8a
          cp libpdf2pclm.so ../libs/arm64-v8a/
