      - name: 安装构建依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libgs-dev \
            ghostscript \
            libnode-dev

      - name: 构建 gs_napi.so
        working-directory: native
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel

      - name: 准备 so 文件目录
        run: mkdir -p entry/src/main/resources/libs/arm64-v8a

      - name: 拷贝 gs_napi.so
        run: cp native/build/gs_napi.so entry/src/main/resources/libs/arm64-v8a/

      - name: 拷贝 libgs.so
        run: |
          cp /usr/lib/x86_64-linux-gnu/libgs.so \
             entry/src/main/resources/libs/arm64-v8a/

      - name: Upload SO artifacts
        uses: actions/upload-artifact@v4
        with:
          name: so-packages
          path: |
            entry/src/main/resources/libs/arm64-v8a/gs_napi.so
            entry/src/main/resources/libs/arm64-v8a/libgs.so

      - name: 验证 gs CLI 安装
        run: |
          gs --version    # 现在应该能正确输出版本号了
