# .github/workflows/build-static.yml
name: Build Static pdf2pclm.node

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3 \
            zlib1g-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev

      - name: Install npm dependencies
        run: npm install

      - name: Debug napi include path
        run: node -p "require('node-addon-api').include"

      - name: Build Ghostscript (static)
        run: |
          git clone --depth=1 git://git.ghostscript.com/ghostpdl.git
          cd ghostpdl/ghostscript
          ./configure --disable-shared --enable-static
          make -j$(nproc)
          cp soobj/libgs.a $GITHUB_WORKSPACE/
          cp -r base $GITHUB_WORKSPACE/gs-headers

      - name: Build native addon
        run: |
          npx node-gyp configure
          npx node-gyp build

      - name: Upload pdf2pclm.node
        uses: actions/upload-artifact@v4
        with:
          name: pdf2pclm-static-node
          path: build/Release/pdf2pclm.node
