name: CI Build libs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-libs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake libgs-dev ghostscript libnode-dev

      - name: Build libgs_napi.so
        working-directory: native
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel
          cp build/libgs_napi.so $GITHUB_WORKSPACE

      - name: Copy libgs.so
        run: cp /usr/lib/x86_64-linux-gnu/libgs.so $GITHUB_WORKSPACE

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: |
            libgs_napi.so
            libgs.so
