name: Build & Upload SO Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 安装构建依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libgs-dev \
            ghostscript \
            libnode-dev

      - name: 构建 gs_napi.so
        run: |
          cd native
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel

      - name: 准备 SO 目录
        run: mkdir -p entry/src/main/resources/libs/arm64-v8a

      - name: 拷贝 so 文件
        run: |
          cp native/build/gs_napi.so entry/src/main/resources/libs/arm64-v8a/
          cp /usr/lib/x86_64-linux-gnu/libgs.so entry/src/main/resources/libs/arm64-v8a/

      - name: 上传 SO Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: so-packages
          path: |
            entry/src/main/resources/libs/arm64-v8a/gs_napi.so
            entry/src/main/resources/libs/arm64-v8a/libgs.so
