name: Build HarmonyOS Ghostscript Library

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  OHOS_NDK_VERSION: "4.0.10.6"
  GHOSTSCRIPT_VERSION: "10.03.0"
  LIBRARY_NAME: "pdf_converter"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # ... [其他步骤保持不变] ...

    - name: Build with CMake
      run: |
        mkdir build && cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=${{ env.OHOS_NDK_PATH }}/build/cmake/ohos.toolchain.cmake \
          -DOHOS_ARCH=arm64-v8a \
          -DOHOS_STL=c++_shared \
          -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        
        # 重命名SO文件以兼容鸿蒙命名规范
        mv lib${{ env.LIBRARY_NAME }}.so lib${{ env.LIBRARY_NAME }}.z.so

    - name: Verify output
      run: |
        cd build
        file lib${{ env.LIBRARY_NAME }}.z.so
        # 确认文件类型应为：ELF 64-bit LSB shared object, ARM aarch64

    # 修复：使用 upload-artifact@v4 并添加压缩选项
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: harmony-pdf-converter
        path: build/lib${{ env.LIBRARY_NAME }}.z.so
        compression-level: 0  # 禁用压缩以避免损坏二进制文件
        overwrite: true
