name: CI Build libs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-libs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake libgs-dev ghostscript libnode-dev

      - name: Build native libraries
        working-directory: native
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel

      - name: Copy .so to entry/resources
        run: |
          mkdir -p entry/src/main/resources/libs/arm64-v8a
          # 如果你在 CMakeLists 指定了 PREFIX ""，直接是 gs_napi.so
          cp native/build/gs_napi.so entry/src/main/resources/libs/arm64-v8a/
          # Ghostscript 运行时库
          cp /usr/lib/x86_64-linux-gnu/libgs.so entry/src/main/resources/libs/arm64-v8a/
