# .github/workflows/build-and-upload-so.yml
name: Build & Upload SO Artifacts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 安装构建依赖
        run: |
          sudo apt-get update
          # 下面一行千万别带注释，否则反斜杠不会起作用  
          sudo apt-get install -y \
            build-essential \
            cmake \
            libgs-dev \
            libnode-dev

      - name: 构建 gs_napi.so
        working-directory: native
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel

      - name: 准备 so 文件目录
        run: mkdir -p entry/src/main/resources/libs/arm64-v8a

      - name: 拷贝 gs_napi.so
        run: cp native/build/gs_napi.so entry/src/main/resources/libs/arm64-v8a/

      - name: 拷贝 libgs.so
        run: |
          # 直接在系统库里找 libgs.so，CLI 的包无需安装
          cp /usr/lib/x86_64-linux-gnu/libgs.so \
             entry/src/main/resources/libs/arm64-v8a/

      - name: Upload SO artifacts
        uses: actions/upload-artifact@v4
        with:
          name: so-packages
          path: |
            entry/src/main/resources/libs/arm64-v8a/gs_napi.so
            entry/src/main/resources/libs/arm64-v8a/libgs.so

      - name: （可选）Smoke test gs CLI
        run: |
          # 如果你想验证系统里有没有 gs
          gs --version
