name: CI Build & Test libgs_napi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake libgs-dev ghostscript

    - name: Build libgs_napi.so
      working-directory: native
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel
        cp build/libgs_napi.so ${{ github.workspace }}/

    - name: Compile and run test
      run: |
        cp tests/test.pdf test.pdf
        g++ tests/test_main.cpp \
          -L native/build -lgs_napi -lgs -o test_main
        LD_LIBRARY_PATH=./native/build:$LD_LIBRARY_PATH \
          ./test_main test.pdf output.pclm
      env:
        LD_LIBRARY_PATH: ${{ github.workspace }}/native/build:${LD_LIBRARY_PATH}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gs-napi-results
        path: |
          libgs_napi.so
          output.pclm
          test.pdf
          test_main
