name: Build Ghostscript for HarmonyOS

on:
  push:
  pull_request:

jobs:
  build-libgs:
    runs-on: ubuntu-latest
    env:
      CLI_URL: "https://contentcenter-vali-drcn.dbankcdn.cn/pvt_2/DeveloperAlliance_package_901_9/f6/v3/s4KXxlxTQBamLt4g2wT0Hg/commandline-tools-linux-x64-5.1.0.840.zip?HW-CC-KV=V1&HW-CC-Date=20250714T092621Z&HW-CC-Expire=7200&HW-CC-Sign=43C91A44AF943C8DCC41AE5DBA2CF54CE6A3EE23FA7DCAA91A67384C2C3E2FB1"
      GS_VERSION: ${{ secrets.GS_VERSION }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip p7zip-full \
            autoconf automake libtool cmake pkg-config \
            zlib1g-dev libpng-dev libtiff5-dev

      - name: Download & extract HMOS CLI
        run: |
          wget -O hmos-cli.zip "${CLI_URL}"
          unzip -q hmos-cli.zip -d hmos
          # …设环境变量 cross-compiler …

      - name: Build libgs.so
        run: |
          git clone https://git.ghostscript.com/ghostpdl.git
          cd ghostpdl
          [ -n "$GS_VERSION" ] && git fetch --tags && git checkout "$GS_VERSION"
          ./autogen.sh
          ./configure --host=aarch64-unknown-linux-gnu \
            --disable-gtk --disable-fontconfig --disable-compile-inits \
            --with-device-list=pclm \
            CC=$CC CXX=$CXX \
            CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS"
          make -j$(nproc)
          make install DESTDIR=$(pwd)/build_output

      - name: Debug install tree
        run: |
          echo "=== build_output/usr/local ==="
          find ghostpdl/build_output/usr/local -maxdepth 2 | sed 's/^/→ /'

      - name: Upload libgs.so
        uses: actions/upload-artifact@v4
        with:
          name: ghostscript-libs
          path: ghostpdl/build_output/usr/local/lib/libgs.so
